language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-safari-push' ]; then cd .. && eval "mv $currentfolder generator-safari-push" && cd generator-safari-push; fi

